# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='专题名称')),
                ('cover_image', models.ImageField(default='image/foodtopic.jpg', upload_to='topic/cover/%Y/%m/%d', verbose_name='封面图片')),
                ('description', models.TextField(verbose_name='专题描述')),
                ('total_collects', models.PositiveIntegerField(db_index=True, default=0, verbose_name='收藏数')),
                ('tags', models.CharField(default='', max_length=64, verbose_name='专题标签')),
                ('foods', models.ManyToManyField(related_name='topics_belong', to='food.Food', verbose_name='美食')),
                ('users_collect', models.ManyToManyField(blank=True, related_name='topics_collected', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户')),
            ],
            options={
                'verbose_name_plural': '美食专题',
                'verbose_name': '美食专题',
            },
        ),
    ]
