# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_foodtopic_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtopic',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='foodtopic',
            name='users_collect',
        ),
    ]
