# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20170703_1440'),
        ('topic', '0003_auto_20170629_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtopic',
            name='food',
            field=models.ManyToManyField(related_name='topics_belong', to='food.Food', verbose_name='包含美食'),
        ),
    ]
