# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0004_foodtopic_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtopic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics_shared', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
    ]
