# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0004_auto_20170629_1510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_auto_20170629_1510'),
        ('topic', '0003_auto_20170629_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='美食')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.FoodTopic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name_plural': '食物和专题',
                'verbose_name': '食物和专题',
            },
        ),
        migrations.CreateModel(
            name='UserCollectTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.FoodTopic', verbose_name='收藏的专题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户收藏的专题',
                'verbose_name': '用户收藏的专题',
            },
        ),
        migrations.CreateModel(
            name='UserHaveAte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='吃过的食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户吃过的食物',
                'verbose_name': '用户吃过的食物',
            },
        ),
        migrations.CreateModel(
            name='UserRecommendForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ForumPost', verbose_name='推荐的帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户推荐的帖子',
                'verbose_name': '用户推荐的帖子',
            },
        ),
        migrations.CreateModel(
            name='UserWantEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='想吃的食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户想吃的食物',
                'verbose_name': '用户想吃的食物',
            },
        ),
    ]
