# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_userdislikefood_userlikefood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodintopic',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodintopic',
            name='topic',
        ),
        migrations.DeleteModel(
            name='FoodInTopic',
        ),
    ]
