# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(default='', max_length=128, verbose_name='食品名称'),
        ),
    ]
