# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20170625_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='rating_dislikes',
        ),
        migrations.RemoveField(
            model_name='food',
            name='rating_likes',
        ),
        migrations.RemoveField(
            model_name='food',
            name='users_ate',
        ),
        migrations.RemoveField(
            model_name='food',
            name='users_wta',
        ),
        migrations.AlterField(
            model_name='food',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='来源链接'),
        ),
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.CharField(default='', help_text="请使用','将多个标签分隔开", max_length=64, verbose_name='食物标签'),
        ),
    ]
