# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_total_likenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='total_atenum',
            field=models.PositiveIntegerField(default=0, verbose_name='吃过这个美食的用户总数'),
        ),
        migrations.AddField(
            model_name='food',
            name='total_dislikenum',
            field=models.PositiveIntegerField(default=0, verbose_name='不喜欢总数'),
        ),
        migrations.AddField(
            model_name='food',
            name='total_wantnum',
            field=models.PositiveIntegerField(default=0, verbose_name='想吃这个美食的用户总数'),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_likenum',
            field=models.PositiveIntegerField(default=0, verbose_name='喜欢总数'),
        ),
    ]
