# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='content',
        ),
    ]
