# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170616_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, max_length=256, null=True, upload_to='user/background_img/%Y/%m/%d', verbose_name='主页背景')),
            ],
            options={
                'verbose_name_plural': '用户设置',
                'verbose_name': '用户设置',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='background_image',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
