# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170616_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default=' ', max_length=32, verbose_name='个人邮箱'),
        ),
    ]
