# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170619_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=32, verbose_name='个人邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', max_length=16, verbose_name='昵称'),
        ),
    ]
