# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170625_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
