# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170629_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_likenum',
            field=models.PositiveIntegerField(default=0, verbose_name='用户吃过的美食的总数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_wantnum',
            field=models.PositiveIntegerField(default=0, verbose_name='用户想吃的美食的总数'),
        ),
    ]
