# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 15:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255, verbose_name='活动描述')),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='活动对象id')),
                ('add_time', models.DateTimeField(db_index=True, default=datetime.datetime(2017, 7, 10, 15, 5, 32, 120489), verbose_name='活动时间')),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.ContentType', verbose_name='活动对象的类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '活动',
                'verbose_name': '活动',
            },
        ),
    ]
