# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='add_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 7, 10, 15, 8, 39, 343987), verbose_name='活动时间'),
        ),
    ]
