# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_auto_20170712_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='add_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 7, 12, 18, 7, 34, 193947), verbose_name='活动时间'),
        ),
    ]
