# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 18:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20170617_0643'),
        ('usercomments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=512, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog', verbose_name='博文')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '博文评价',
                'verbose_name_plural': '博文评价',
            },
        ),
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'verbose_name': '帖子评价', 'verbose_name_plural': '帖子评价'},
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='blog',
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='forum_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.ForumPost', verbose_name='帖子'),
        ),
    ]
