# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default='', max_length=128, verbose_name='标题'),
        ),
    ]
