# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='', max_length=32, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_name',
            field=models.CharField(default='', max_length=32, verbose_name='省份名称'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='', max_length=64, verbose_name='店铺名称'),
        ),
    ]
