# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_store_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='province',
        ),
    ]
