# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 09:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('food_name', models.CharField(default=' ', max_length=128, verbose_name='食品名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('cover_image', models.ImageField(default='image/dangao.jpg', max_length=128, upload_to='food/cover/%Y/%m/%d', verbose_name='封面图片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='相关链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tags', models.CharField(default='', max_length=64, verbose_name='食物标签')),
                ('rating_likes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('rating_dislikes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': '食物信息',
                'verbose_name_plural': '食物信息',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='好吃的', max_length=64, verbose_name='食品种类')),
            ],
            options={
                'verbose_name': '食品种类',
                'verbose_name_plural': '食品种类',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods_shared', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='food',
            name='users_ate',
            field=models.ManyToManyField(blank=True, related_name='foods_ate', to=settings.AUTH_USER_MODEL, verbose_name='吃过的用户'),
        ),
        migrations.AddField(
            model_name='food',
            name='users_wta',
            field=models.ManyToManyField(blank=True, related_name='foods_wta', to=settings.AUTH_USER_MODEL, verbose_name='想吃的用户'),
        ),
    ]
