# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 06:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default=' ', max_length=32, verbose_name='名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '板块信息',
                'verbose_name_plural': '板块信息',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=64, verbose_name='帖子标题')),
                ('content', models.TextField(max_length=5096, verbose_name='帖子内容')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('total_likes', models.IntegerField(default=0, verbose_name='推荐数')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Board', verbose_name='所属板块')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('users_like', models.ManyToManyField(blank=True, related_name='forumposts_liked', to=settings.AUTH_USER_MODEL, verbose_name='推荐的用户')),
            ],
            options={
                'verbose_name': '帖子信息',
                'verbose_name_plural': '帖子信息',
            },
        ),
    ]
