# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='creator',
            new_name='board_creator',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='content',
            new_name='forum_content',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='creator',
            new_name='forum_creator',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='title',
            new_name='forum_title',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='updated',
            new_name='updated_time',
        ),
    ]
