# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170617_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='forum_title',
            field=models.CharField(default='', max_length=64, verbose_name='帖子标题'),
        ),
    ]
