# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170625_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='total_likes',
            new_name='recommend_num',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='users_like',
        ),
    ]
